import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { closeSync, constants, fstatSync, openSync, readSync, realpathSync } from "node:fs";
import { basename, isAbsolute, relative, resolve } from "node:path";
import type { ReviewLine } from "./review/types.ts";

const limit = 1024 * 1024;
export function reviewOptions(args: string) {
  const match = /^\s*--all-files(?:\s+|$)/.exec(args);
  return { allFiles: Boolean(match), args: match ? args.slice(match[0].length) : args };
}

export function isTestPath(path: string): boolean {
  return /(^|\/)(__tests__|tests?)(\/)/.test(path) ||
    /(?:_test\.go|(?:^|\/)test_[^/]*\.py|_test\.py|\.(?:test|spec)\.[cm]?[jt]sx?|(?:Test|Tests|TestCase)\.(?:java|kt|scala|cs)|_spec\.rb|_test\.rb)$/.test(path);
}

export function generatedHeader(text: string): boolean {
  let block = false;
  for (const raw of text.slice(0, 65536).split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#!")) continue;
    const comment = block || /^(?:\/\/|#|\/\*|\*|<!--|--\s)/.test(line);
    if (!comment) break;
    if (/^(?:\/\*|<!--)/.test(line)) block = true;
    if (/\*\/|-->/.test(line)) block = false;
    if (/^\/\/ Code generated .+ DO NOT EDIT\.$/.test(line) ||
        /(?:auto[- ]generated|automatically generated|generated by|<auto-generated\b)/i.test(line) &&
        /(?:do not edit|do not modify|<auto-generated\b)/i.test(line)) return true;
  }
  return false;
}

function git(cwd: string, args: string[], input = ""): Buffer | undefined {
  const result = spawnSync("git", args, { cwd, input, maxBuffer: 16 * limit, timeout: 10000, env: { ...process.env, GIT_OPTIONAL_LOCKS: "0" } });
  return !result.error && result.status === 0 ? result.stdout : undefined;
}

function inside(root: string, path: string): boolean {
  const rel = relative(root, path);
  return rel !== ".." && !rel.startsWith("../") && !isAbsolute(rel);
}

function readContent(path: string, root?: string): Buffer | undefined {
  let fd: number | undefined;
  try {
    if (root && (!inside(root, path) || !inside(realpathSync(root), realpathSync(path)))) return;
    fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK);
    const stat = fstatSync(fd);
    if (!stat.isFile() || stat.size > limit) return;
    const content = Buffer.alloc(stat.size + 1);
    const length = readSync(fd, content, 0, content.length, 0);
    return length === stat.size ? content.subarray(0, length) : undefined;
  } catch { return; }
  finally { if (fd != null) closeSync(fd); }
}

function blobs(cwd: string, ids: string[]): Map<string, Buffer> {
  const found = new Map<string, Buffer>();
  if (!ids.length) return found;
  const sizes = git(cwd, ["cat-file", "--batch-check"], ids.join("\n") + "\n");
  if (!sizes) return found;
  const wanted = sizes.toString().trim().split("\n").flatMap((line, i) => {
    const match = /^(\w+) blob (\d+)$/.exec(line);
    return match && Number(match[2]) <= limit ? [{ id: ids[i], oid: match[1], size: Number(match[2]) }] : [];
  });
  let total = 0;
  const bounded = wanted.filter(item => {
    total += item.size;
    return total < 12 * limit;
  });
  if (!bounded.length) return found;
  const data = git(cwd, ["cat-file", "--batch"], bounded.map(item => item.oid).join("\n") + "\n");
  if (!data) return found;
  let offset = 0;
  for (const item of bounded) {
    const end = data.indexOf(10, offset);
    const match = /^(\w+) blob (\d+)$/.exec(data.subarray(offset, end).toString());
    if (!match) break;
    const size = Number(match[2]);
    offset = end + 1;
    found.set(item.id, data.subarray(offset, offset + size));
    offset += size + 1;
  }
  return found;
}

export function filterReview(cwd: string, lines: ReviewLine[], mode: "diff" | "view", allFiles: boolean) {
  if (allFiles) return { lines, summary: "", cacheMode: "all-files" };
  const root = git(cwd, ["rev-parse", "--show-toplevel"])?.toString().replace(/\r?\n$/, "");
  const groups = new Map<string, ReviewLine[]>();
  for (const line of lines) {
    if (!line.filePath) continue;
    const group = groups.get(line.filePath) ?? [];
    group.push(line);
    groups.set(line.filePath, group);
  }
  const paths = [...groups.keys()];
  const absolute = (path: string) => resolve(root ?? cwd, path);
  const names = new Map(paths.map(path => [path, inside(root ?? cwd, absolute(path)) ? relative(root ?? cwd, absolute(path)) : basename(path)]));
  const attrs = new Map<string, string>();
  if (root) {
    const eligible = paths.filter(path => inside(root, absolute(path)));
    const output = git(root, ["check-attr", "-z", "--stdin", "linguist-generated"], eligible.map(path => relative(root, absolute(path))).join("\0") + "\0");
    const fields = output?.toString().split("\0") ?? [];
    for (let i = 0; i + 2 < fields.length; i += 3) attrs.set(fields[i], fields[i + 2]);
  }
  const ids = new Map<string, string>();
  if (mode === "diff") for (const [path, group] of groups) {
    const index = group.find(line => line.kind === "meta" && /^index [a-f\d]+\.\.[a-f\d]+/.test(line.text));
    const match = index?.text.match(/^index ([a-f\d]+)\.\.([a-f\d]+)/);
    if (match) ids.set(path, /^0+$/.test(match[2]) ? match[1] : match[2]);
  }
  const contents = blobs(cwd, [...new Set(ids.values())].filter(id => !/^0+$/.test(id)));
  const hidden = new Set<string>();
  let tests = 0;
  let generated = 0;
  for (const path of paths) {
    const name = names.get(path)!;
    if (isTestPath(name)) { hidden.add(path); tests++; continue; }
    const attr = attrs.get(name);
    if (attr === "false" || attr === "unset") continue;
    let content: Buffer | undefined;
    if (mode === "view") content = Buffer.from(groups.get(path)!.filter(line => line.kind === "context").slice(0, 1000).map(line => line.text.slice(1)).join("\n"));
    else {
      const id = ids.get(path);
      content = id ? contents.get(id) : undefined;
      if (!content && id && root && !/^0+$/.test(id)) {
        const candidate = readContent(absolute(path), root);
        if (candidate) {
          const algorithm = id.length > 40 ? "sha256" : "sha1";
          const hash = createHash(algorithm).update(`blob ${candidate.length}\0`).update(candidate).digest("hex");
          if (hash.startsWith(id)) content = candidate;
        }
      }
    }
    if (!content && mode === "diff") {
      const group = groups.get(path)!;
      const deleted = group.some(line => line.text === "+++ /dev/null" || line.text.startsWith("deleted file mode "));
      const prefix: string[] = [];
      let expected = 1;
      for (const line of group) {
        const number = deleted ? line.oldLineNumber : line.newLineNumber;
        if (number == null) continue;
        if (number !== expected++) break;
        prefix.push(line.text.slice(1));
        if (prefix.length >= 1000) break;
      }
      content = Buffer.from(prefix.join("\n"));
    }
    if (attr === "true" || attr === "set" || content && generatedHeader(content.toString())) {
      hidden.add(path); generated++;
    }
  }
  return {
    lines: lines.filter(line => !line.filePath || !hidden.has(line.filePath)),
    summary: hidden.size ? `Hidden ${tests} test and ${generated} generated files. Use --all-files to include them.` : "",
    cacheMode: "filtered-v1",
  };
}
