import assert from 'node:assert/strict';
import { createJiti } from 'jiti';
import { join } from 'node:path';
const [source, directory] = process.argv.slice(2);
const jiti = createJiti(import.meta.url);
const { TeamStore, processIdentity } = await jiti.import(join(source, 'pi-extension/subagents/team.ts'));
const store = TeamStore.create(directory);
const member = { id: 'same-process', name: 'same-process', parent: null, live: true, pid: process.pid, processIdentity: processIdentity(process.pid) };
const old = await store.register(member);
assert.equal(typeof old, 'string', 'registration returns its captured incarnation');
const replacement = await store.register({ ...store.state().members[member.id] });
assert.notEqual(old, replacement, 'even an identical registration gets a new incarnation');
assert.equal(store.state().members[member.id].incarnation, replacement);
assert.equal(await store.retire(member.id, old), false, 'stale shutdown cannot retire same-process replacement');
assert.equal(await store.retireIfQuiet(member.id, old, new Set()), false, 'stale quiet retirement cannot retire same-process replacement');
assert.equal(store.state().members[member.id].live, true);
assert.equal(await store.retireIfQuiet(member.id, replacement, new Set(), () => false), false, 'local eligibility remains enforced');
assert.equal(store.state().members[member.id].live, true);
assert.equal(await store.retireIfQuiet(member.id, replacement, new Set()), true);
assert.equal(store.state().members[member.id].live, false);
const resumed = await store.register(member);
assert.equal(await store.retire(member.id, resumed), true);
assert.equal(store.state().members[member.id].live, false);
await store.cancelTree(member.id);
await assert.rejects(store.register(member), /Ancestor was cancelled/);
await assert.rejects(store.register({ ...member, id: 'descendant', parent: member.id }), /Ancestor was cancelled/);
console.log('PASS same-process incarnation fencing, eligibility and cancellation invariants');
