import assert from 'node:assert/strict';
import { createJiti } from 'jiti';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const [source, directory] = process.argv.slice(2);
mkdirSync(directory, { recursive: true });
const { TeamStore, reserveTeamChild } = await createJiti(import.meta.url).import(join(source, 'pi-extension/subagents/team.ts'));
process.env.PI_TEAM_DIR = join(directory, 'team'); process.env.PI_TEAM_MEMBER = 'root';
const store = TeamStore.create(process.env.PI_TEAM_DIR);
await store.register({ id: 'root', name: 'root', parent: null, live: true });
await store.setDesired(true);
const old = await store.register({ id: 'old', name: 'worker', parent: 'root', live: true });
await store.cancelTree('old', old);
await store.retire('old', old);
const sessionFile = join(directory, 'worker.jsonl');
writeFileSync(`${sessionFile}.team.json`, JSON.stringify({ dir: store.dir, id: 'old' }));
const resumed = await reserveTeamChild({ sessionManager: { getSessionId: () => 'root' } }, 'worker', sessionFile, '');
assert.notEqual(resumed.id, 'old', 'cancelled saved incarnation remains fenced');
await store.register({ id: 'stale-process', name: 'worker', parent: 'root', live: true, pid: process.pid, processIdentity: 'not-the-current-process' });
const delivered = await store.send('root', { to: 'worker', message: 'resumed worker DM' });
assert.deepEqual(delivered.recipients, [resumed.id, 'root'], 'named DM selects the one eligible resumed worker');
assert.equal(await store.retire(resumed.id, old), false, 'old incarnation cannot retire resumed registration');
await assert.rejects(store.send('root', { to: 'old', message: 'do not revive completed id' }), /completed/);
await store.register({ id: 'second-live', name: 'worker', parent: 'root', live: true });
await assert.rejects(store.send('root', { to: 'worker', message: 'genuinely ambiguous' }), /ambiguous/);
writeFileSync(join(directory, 'result.json'), JSON.stringify({ delivered, state: store.state() }, null, 2));
console.log('PASS resumed named DM ignores historical member and preserves multiple-live ambiguity/stale fencing');
